// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Error': string;
  'Form': string;
  'Group': string;
  'Input': string;
  'InputError': string;
}
declare var cssExports: CssExports;
export = cssExports;
